services:
  postgres:
    container_name: time-postgres
    hostname: time-postgres
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - TZ='Asia/Tokyo'
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - postgres-nw

networks:
  postgres-nw:
    driver: bridge
